
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

EXPOSE 5000

# Prisma генерується кожного разу при старті контейнера
CMD ["sh", "-c", "npx prisma generate && npm run dev"]


